### PR TITLE
Finishes up catalog#show design updates

### LINKED ISSUE #1419: Redo record page layout
Update the record page layout inline with the designs delivered from the designers, with the few exceptions noted in the updated version I sent.

- [x] Description, Credits, Holdings, and Citation bars added
- [x] Description defaults to open, every other section defaults to closed
- [x] If there is no credit information show a message [TBD]
- [x] Add colors to the Transcript search bar.

### LINKED ISSUE #1425: Add holdings information
Map data from the pbcore instantiations, so we can display it as individual holdings entries. See designs from Creative. 
*note to self on mapping: Casey wants the local asset ids to appear in this section, not just the instantiations ids.

### LINKED ISSUE #1442: Update solr data model to accomodate new display for record pages

### PR DESCRIPTION
**Pull request by jasoncorum**
@afred @sroosa - this is ready for review. @sroosa, am i remembering correctly we'll have to reindex some records once we push this to demo?

Since these tickets were all inter-related they're rolled up in to this one branch.

* Closes #1425
* Closes #1419
* Closes #1442

### CODE REVIEW

**Comment by jasoncorum** [comment]
@sroosa - sure thing! let me know when you want to demo and i can set up the ssh tunnel to my local.

File: app/assets/javascripts/player.js [hunk 1]
```diff
@@ -128,115 +128,33 @@ $(function(){
...
+        var slide = sliders[i];
+        if (slide.classList.contains('show-transcript')) {
+          slide.innerHTML = 'Show<div class="transcript-circle">+</div>';
+          slide.classList.remove('show-transcript');
+          search.removeClass('show-transcript-search');
+        } else if (!slide.classList.contains('show-transcript')) {
+          slide.innerHTML = 'Hide<div class="transcript-circle">-</div>';
+          slide.classList.add('show-transcript');
+          search.addClass('show-transcript-search');
+        };
```
Comment (afred) [inline app/assets/javascripts/player.js]: @jasoncorum What does this end up looking like?

File: spec/fixtures/transcripts/cpb-aacip-111-21ghx7d6-transcript.html [hunk 2]
```diff
@@ -1,362 +1,288 @@
...
+</div>
+</div>
+<div class="transcript-row">
+<span class="play-from-here" data-timecode="00:08:39.190"> </span><div id="para9" class="para" data-timecodebegin="00:08:39.190" data-timecodeend="00:09:06.960">We are not commercial and we must be wary even as we are being permit
```
Comment (afred) [inline spec/fixtures/transcripts/cpb-aacip-111-21ghx7d6-transcript.html]: Is this just indentation diffs? And if so, why is it needed?

File: spec/features/catalog_spec.rb [hunk 3]
```diff
@@ -431,7 +431,7 @@ def expect_all_the_text(fixture_name)
       expect_transcript
     end
 
-    it 'has a transcript if expected' do
+    it 'has no transcript if expected' do
```
Comment (afred) [inline spec/features/catalog_spec.rb]: good catch!

File: app/assets/javascripts/mobile-transcript.js [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+          if (currentIndex > $mobileResults.length - 1) {
+            currentIndex = 0;
+          }
+          jumpTo();
+        }
+      });
+    });
+  });
+});
+
```
Comment (afred) [inline app/assets/javascripts/mobile-transcript.js]: Is this functionally the same as `transcript.js`? The only difference I can see are the CSS selectors, and variable names.

Comment (jasoncorum) [reply app/assets/javascripts/mobile-transcript.js]: yes and this could totally get dry-ed out. originally i was using the same JS for both the regular and mobile transcripts and it seemed to work fine on initial testing. but then toward the end of my work i realized that using the same JS was pulling the text from both transcripts for highlighting search results so you'd be cycling through both the visible and invisible results. d'oh! i'd been working on it for too long so went with a simple and fast fix.

Comment (afred) [reply app/assets/javascripts/mobile-transcript.js]: 👌

File: app/assets/javascripts/player.js (hunk 1 above)
Comment (jasoncorum) [reply app/assets/javascripts/player.js]: Open:
screen shot 2018-05-17 at 2 45 55 pm

Closed:
screen shot 2018-05-17 at 2 46 13 pm

**Comment by jasoncorum** [comment]
For posterity's sake, here are the designs we received.

[AAPB_web_redesign_FINAL2.pdf](https://github.com/WGBH/AAPB2/files/2014844/AAPB_web_redesign_FINAL2.pdf)

File: spec/fixtures/transcripts/cpb-aacip-111-21ghx7d6-transcript.html (hunk 2 above)
Comment (jasoncorum) [reply spec/fixtures/transcripts/cpb-aacip-111-21ghx7d6-transcript.html]: yep. for some reason existing tests were really picky about the small updates i made to how we generate the html for transcripts.

File: spec/features/catalog_spec.rb (hunk 3 above)
Comment (jasoncorum) [reply spec/features/catalog_spec.rb]: of my own mistake! :)

**Comment by jasoncorum** [comment]
Not sure if tests will pass or if I'll have to pull and make updates. We added some new fixtures in the PRs, so the totals and expectations there might need adjusting.
